export function fetchGroups(){
	return {
		type: "FETCH_GROUPS_FULLFILED",
		payload : [
				{id:1, name:'Triceps'},
				{id:2, name:'Biceps'},
				{id:3, name:'Quadricep Compound'},
				{id:4, name:'Quadricep Isolation'},
				{id:5, name:'Hamstring Compound'},
				{id:6, name:'Hamstring Isolation'},
				{id:7, name:'Glutes'},
				{id:8, name:'Calves'},
				{id:9, name:'Chest Compound'},
				{id:10, name:'Chest Isolation'},
				{id:11, name:'Shoulder'},
				{id:12, name:'Lateral Deltoid'},
				{id:13, name:'Posterior Deltoid'},
				{id:14, name:'Back'},
				{id:15, name:'Abdominals'},
				{id:16, name:'Squat'},
				{id:17, name:'Dead Lift'},
				{id:18, name:'Bench Press'}
		]
	}
}

export function fetchExercises(){
	return {
		type: "FETCH_EXERCISES_FULLFILED",
		payload : [ 
			{id:1, group:"Triceps", name:"Tricep Straight Bar Pushdowns (Cable Machine)"},
			{id:2, group:"Triceps", name:"Tricep Rope Pulldowns (Cable Machine)"},
			{id:3, group:"Triceps", name:"Tricep Skull Crushers (Curl Bar)"},
			{id:4, group:"Triceps", name:"Tricep Close Grip Bench Press (Barbell)"},
			{id:5, group:"Triceps", name:"Tricep Kickback (Dumbbell)"},
			{id:6, group:"Biceps", name:"Bicep Concentration Curl (Dumbbell)"},
			{id:7, group:"Biceps", name:"Bicep Seated Curl (Dumbbell)"},
			{id:8, group:"Biceps", name:"Bicep Preacher Curl (Curl Bar)"},
			{id:9, group:"Biceps", name:"Bicep Curl (Barbell)"},
			{id:10, group:"Quadricep Compound", name:"Hack Squat (Machine)"},
			{id:11, group:"Quadricep Compound", name:"Front Squat (Barbell)"},
			{id:12, group:"Quadricep Compound", name:"Leg Press"},
			{id:13, group:"Quadricep Isolation", name:"Leg Extensions"},
			{id:14, group:"Quadricep Isolation", name:"Leg Extensions (Single Leg)"},
			{id:15, group:"Quadricep Isolation", name:"Static Lunge (Dumbbell)"},
			{id:16, group:"Quadricep Isolation", name:"Rear Foot Elevated Lunge"},
			{id:17, group:"Hamstring Compound", name:"Stiff Legged Deadlift (Barbell)"},
			{id:18, group:"Hamstring Isolation", name:"Hamstring Curls (Machine)"},
			{id:19, group:"Hamstring Isolation", name:"Single Hamstring Curls (Machine)"},
			{id:20, group:"Glutes", name:"Glute Bridge (Barbell)"},
			{id:21, group:"Calves", name:"Standing Calf Raise (Machine)"},
			{id:22, group:"Calves", name:"Seated Calf Raise (Machine)"},
			{id:23, group:"Chest Compound", name:"Decline Chest Press (Dumbbell)"},
			{id:24, group:"Chest Compound", name:"Decline Chest Press (Barbell)"},
			{id:25, group:"Chest Compound", name:"Flat Chest Press (Dumbbell)"},
			{id:26, group:"Chest Compound", name:"Chest Press Machine"},
			{id:27, group:"Chest Isolation", name:"Chest Cable Fly (Machine)"},
			{id:28, group:"Chest Isolation", name:"Decline Fly (Dumbbell)"},
			{id:29, group:"Chest Isolation", name:"Flat Bench Fly (Dumbbell)"},
			{id:30, group:"Shoulder", name:"Standing Shoulder Press (Barbell)"},
			{id:31, group:"Shoulder", name:"Seated Shoulder Press (Barbell)"},
			{id:32, group:"Shoulder", name:"Seated Shoulder Press (Dumbbell)"},
			{id:33, group:"Shoulder", name:"Machine Shoulder Press"},
			{id:34, group:"Lateral Deltoid", name:"Shoulder Side Lateral Raise (Dumbbell)"},
			{id:35, group:"Lateral Deltoid", name:"Upright Row"},	
			{id:36, group:"Posterior Deltoid", name:"Shoulder Reverse Fly (Machine)"},
			{id:37, group:"Posterior Deltoid", name:"Shoulder Reverse Fly - Chest Supported (Dumbbell)"},	
			{id:38, group:"Back", name:"Lat Pulldown (Underhand + Narrow Grip)"},	
			{id:39, group:"Back", name:"Lat Pulldown (Regular Overhand Grip)"},	
			{id:40, group:"Back", name:"Single Arm Row (Dumbbell)"},	
			{id:41, group:"Back", name:"Bent Over Row (Barbell)"},	
			{id:42, group:"Back", name:"Chin up (Underhand Grip)"},	
			{id:43, group:"Back", name:"Chin up (Overhand Grip)"},	
			{id:44, group:"Back", name:"Chest Supported Row (Dumbbell)"},	
			{id:45, group:"Back", name:"Seated Cable Row"},	
			{id:46, group:"Back", name:"Machine Back Row (Machine of choice with a chest support)"},	
			{id:47, group:"Back", name:"Close Grip Attachment Pulldown"},
			{id:48, group:"Abdominals", name:"Crunch With Arms Extended"},	
			{id:49, group:"Abdominals", name:"Hanging Leg Raises"},	
			{id:50, group:"Abdominals", name:"Lying Leg Raises"},	
			{id:51, group:"Abdominals", name:"Oblique Side Bends (Dumbbell)"},
			{id:52, group:"Squat", name:"Front Squat (Barbell)"},  
			{id:53, group:"Squat", name:"Leg Press"},  
			{id:54, group:"Squat", name:"Smith Machine Squat"},
			{id:55, group:"Squat", name:"Hack Squat (Machine)"},	  
			{id:56, group:"Dead Lift", name:"Rack Pulls (Barbell)"},	  
			{id:57, group:"Dead Lift", name:"Sumo Dumbbell Dead Lift"},	  
			{id:58, group:"Dead Lift", name:"Sitff Legged Dead Lift"},	  
			{id:59, group:"Bench Press", name:"Decline Chest Press (Barbell)"},
			{id:60, group:"Bench Press", name:"Flat Chest Press (Dumbbell)"},
			{id:61, group:"Bench Press", name:"Machine Chest Press"},

		]	
	}
}
